# Site settings
title: "Chris Kirk: Interactive Journalist"
email: cperryk@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Working at the intersection of journalism and technology.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cperryk.com" # the base hostname & protocol for your site
twitter_username: chrkirk
github_username:  cperryk

# Build settings
markdown: kramdown
